# Custom Language File for Launcher Customizer

[ejs.app]
title = "Minecraft Kartrider Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/X-Cube-Inc/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/eGZfMt8Bam"

[ejs.settings]
sourceGithubLink = "https://github.com/X-Cube-Inc/HeliosLauncher"
supportLink = "https://github.com/X-Cube-Inc/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "마크라이더에 오신걸 환영합니다."
welcomeDescription = "X-Cube는 엔터테인먼트로 시작하였습니다. 하지만, 이제 단순한 엔터테인먼트에서 벗어나 마크라이더로도 진출합니다."
welcomeDescCTA = "최고의 경험과 퍼포먼스를 선사하겠습니다."
